
version: '2'
services:
    bamboo:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8085:8085"
            - "54663:54663"
        stdin_open: true
        tty: true
